spring:
   profiles:
      active: dev-6644
      
---
server:
   port: 6644 
   
spring:
   profiles: dev-6644
   application: 
      name: product-server
      
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/snack_product?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: a
   http:
      encoding:
         charset: utf-8
         force: true
         enabled: true
                  
mybatis:
   # mapper映射问阿金所在的路径
   mapper-locations: mapper/*Mapper.xml
   # 需要启动别名的类的所在的包
   type-aliases-package: com.yc.snack.product.bean 
   
eureka:
   client:
      service-url: 
         defaultZone: http://navy:123321@127.0.0.1:6611/eureka               